ALTER TABLE `song`
    ADD COLUMN `id_spotify_track` VARCHAR(64) NULL COMMENT 'Song identifier at Spotify catalog' AFTER `nm_song_streaming`,
    ADD COLUMN `vl_danceability` DECIMAL(6,5) NULL AFTER `id_spotify_track`,
    ADD COLUMN `vl_energy` DECIMAL(6,5) NULL AFTER `vl_danceability`,
    ADD COLUMN `vl_valence` DECIMAL(6,5) NULL AFTER `vl_energy`,
    ADD COLUMN `vl_acousticness` DECIMAL(6,5) NULL AFTER `vl_valence`,
    ADD COLUMN `vl_instrumentalness` DECIMAL(6,5) NULL AFTER `vl_acousticness`,
    ADD COLUMN `vl_liveness` DECIMAL(6,5) NULL AFTER `vl_instrumentalness`,
    ADD COLUMN `vl_speechiness` DECIMAL(6,5) NULL AFTER `vl_liveness`,
    ADD COLUMN `vl_tempo` DECIMAL(9,4) NULL AFTER `vl_speechiness`,
    ADD COLUMN `id_spotify_key` INT NULL AFTER `vl_tempo`,
    ADD COLUMN `id_spotify_mode` INT NULL AFTER `id_spotify_key`,
    ADD COLUMN `id_time_signature` INT NULL AFTER `id_spotify_mode`,
    ADD COLUMN `vl_loudness` DECIMAL(7,3) NULL AFTER `id_time_signature`,
    ADD COLUMN `id_duration_ms` INT NULL AFTER `vl_loudness`,
    ADD COLUMN `id_analysis_num_bars` INT NULL AFTER `id_duration_ms`,
    ADD COLUMN `id_analysis_num_beats` INT NULL AFTER `id_analysis_num_bars`,
    ADD COLUMN `id_analysis_num_sections` INT NULL AFTER `id_analysis_num_beats`,
    ADD COLUMN `id_analysis_num_segments` INT NULL AFTER `id_analysis_num_sections`,
    ADD COLUMN `id_analysis_num_tatums` INT NULL AFTER `id_analysis_num_segments`;
